var lang = {
  moneyChange: "Konversi kuota",
  totalPay: "Nilai isi ulang",
  totalWithdraw: "Total penarikan",
  fandian: "Perolehan rebate",
  againPay: "Isi ulang 10lagi untuk naik level",
  againPay: "Isi ulang 10lagi untuk naik level",
  noSet: "Belum diatur",
  needPay: "Harus menyetor",
  sport: "Kompetisi olahraga",
  egame: "Permainan elektronik",
  live: "Kasino Live",
  chess: "Permainan catur",
  esport: "E-sports",
  fish: "Fishing",
  betAmount: "Nilai taruhan",
  winAmount: "Nilai hadiah",
  rebateAmount: "Nilai rebate",
  betNum: "Nilai taruhan valid",
  indexHint: "Laba bersih=Nilai hadiah+Pengembalian nilai seri+Rebate taruhan+Rebate agen+Promo+Bonus aktifitas-Nilai taruhan",
  indexRemark: "Catatan: Statistik perbandingan akan mempengaruhi performa sistem, hasil statistik akan dicache 2menit",

  securityLevel: "Level keamanan",
  low: "Rendah",
  middle: "Menengah",
  high: "Tinggi",
  lastLoginTime: "Info log masuk terakhir:",
  loginTime: "Waktu log masuk",
  lastLoginIp: "log masukIP terakhir:",
  loginIp: "log masukIP",
  basicInfo: "Informasi utama",
  realNameHint: "Hubungi layanan konsumen jika nama asli perlu dirubah",
  realName: "Nama asli",
  loginPwd: "Kata sandi log masuk",
  loginPwdHint: "Kata sandi log masuk harus terdiri dari kombinasi6-30 angka dan huruf",
  okPwdHint: "Kata sandi penarikan harus terdiri dari kombinasi4-20 angka dan huruf. Kata sandi penarikan harus diketik jika ingin menarik uang daring",
  phone: "No.HP",
  phoneHint: "Pengikatan No.HP dapat meningkatkan tingkat keamanan akun. Akun akan menjadi lebih aman dan sehat.",
  email: "Surel",
  emailHine: "Pengikatan surel dapat meningkatkan tingkat keamanan akun. Akun akan menjadi lebih aman dan sehat.",
  weChat: "Wechat",
  weChatHint: "Pengikatan Wechat dapat meningkatkan tingkat keamanan akun. Akun akan menjadi lebih aman dan sehat.",
  qqHint: "PengikatanQQdapat meningkatkan tingkat keamanan akun. Akun akan menjadi lebih aman dan sehat",
  facebookHint: "PengikatanFacebookdapat meningkatkan tingkat keamanan akun. Akun akan menjadi lebih aman dan sehat",
  set: "Lakukan pengaturan",
  edit: "Ubah",
  look: "Lihat",
  infoLook: "Lihat informasi utama",
  inputOld: "Ketik QQ sebelumnya",
  inputNew: "KetikQQbaru",
  inputReNew: "KonfirmasiQQbaru",
  reset: "Reset",
  confirm: "Konfirmasi",
  cancel: "Batal",
  formatRrror: "Format salah",
  pleaseInput: "Ketik",
  canNotEmpty: "Tidak boleh kosong",
  canNotSame: "QQsebelumnyadanQQbaru tidak boleh sama",
  twoPutInconformity: "PengetikanQQ2 kalitidak seragam",
  submiting: "Sedang diajukan",

  welcomeLogin: "Selamat datang",
  pwdEdit: "Ganti kata sandi",
  message: "Pesan",
  notice: "Pengumuman Situs",
  imPay: "Segera isi ulang",
  applyAgency: "Permohonan agen",
  pleaseSelect: "Pilih",
  from: "Dari",
  shiftTo: "Transfer masuk",
  outMoney: "Transfer keluar kuota",
  putHint: "Ketik isi",
  surePut: "Konfirmasi transfer keluar",
  moneyChangeHint: "Cat. Auto transfer telah diaktifkan. Segera masuk ke dalam permainan langsung.",
  limitMoney: "Kuota",
  refresh: "Refresh",
  sysMoney: "Kuota sistem",

  status: "Status",
  shiftToType: "Metode transfer masuk",
  sanFangType: "Kategori pihak ketiga",
  transferTime: "Waktu transfer",
  transferType: "Tipe transfer",
  platformText: "Tipe permainan",
  transferMoney: "Nilai transfer",
  transferStatus: "Status transfer",
  allStatus: "Status seluruhnya",
  transferError: "Transfer gagal",
  transferSuccess: "Transfer berhasil",
  transfering: "Sedang diproses",
  moneyChangeAllType: "Metode transfer masuk seluruhnya",
  fromSysToSf: "Transfer dari sistem ke pihak ketiga",
  fromSfToSys: "Transfer dari pihak ketiga ke sistem",
  successText: "Berhasil",
  errorText: "Gagal",

  addText: "Tambah",
  bankRealName: "Nama rekening",
  bankName: "Alamat bank",
  bankCardNo: "Nomor kartu",
  bankStatus: "Status",
  bankTime: "Waktu pengikatan",
  addBank: "Tambah kartu bank",
  bankHint: "Catatan: Penambahan pengikatan kartu bank harus menyediakan info nomor kartu bank yang diikat terakhir yang sedang digunakan!",
  lastBankName: "Nama rekening bank kartu bank terakhir yang diikat",
  lastBankCardNo: "Nomor kartu bank terakhir yang diikat",
  lastBank: "Nama bank",
  pleaseBank: "Pilih bank anda",
  bankName: "Nama pemilik rekening",
  putBankRealName: "Isi nama asli kartu bank",
  putAddress: "Isi alamat kartu bank",
  putNoHint: "Hanya dapat mengetik7-25angka",
  sureBank: "Konfirmasi bank",
  rePutBankNo: "Ketik nomor kartu bank lagi",
  bankOtherHint: "Demi keamanan dana akun anda, ikat no.HP terlebih dahulu",

  scoreExChange: "Tukar poin",
  changeType: "Tipe perubahan",
  beforeScore: "Poin sebelum perubahan",
  scoreNum: "Ganti poin",
  afterScore: "Poin setelah perubahan",
  scoreTime: "Rubah waktu (sistem)",
  remarkText: "Catatan",
  money: "Saldo akun",
  score: "Saldo poin",
  exchangeType: "Metode penukaran",
  moneyToScore: "Uang tunai diganti menjadi poin",
  scoreToMoney: "Poin ditukar menjadi uang tunai",
  exchangeScale: "Proporsi penukaran",
  exchangeMin: "Nilai penukaran minimum",
  exchangeMax: "Nilai penukaran maksimum",
  exchangeNum: "Jumlah penukaran",
  exchangeToNum: "Jumlah konversi",
  notSet: "Belum disetting",
  allText: "Seluruhnya",
  typeActiveSub: "Potong poin event",
  memberSign: "Anggota cek-in",
  depositPresented: "Bonus menyetor",
  peopleAdd: "Tambah manual",
  peopleSub: "Kurang manual",
  activeAdd: "Menghadiahkan poin event",
  active: "Promo",

  orderId: "No. Orderan",
  beforeNum: "Nilai taruhan sebelum perubahan",
  betNum: "Nilai taruhan yang diganti",
  afterNum: "Nilai taruhan setelah perubahan",
  beforeDrawNeed: "Perlu untuk penarikan sebelum perubahan",
  drawNeed: "Perlu untuk penarikan",
  afterDrawNeed: "Perlu untuk penarikan setelah perubahan",
  totalText: "Total",
  regPresent: "Bonus pendaftaran",
  redPacket: "Angpao",
  everyType: "Tambah hadiah setiap hari, kerugian mingguan",
  payText: "Setor",
  activeWin: "Menang undian",
  classPresent: "Bonus naik level",
  fandianEarnings: "Penghasilan rebate agen",
}
