var lang = {
  withdrawPwdNoHint: "Chưa thiết lập mật khẩu rút tiền",
  bankNoHint: "Chưa thiết lập thẻ ngân hàng",
  canWithdraw: "Số tiền có thể rút",
  strategyfeeValue: "Phí thực hiện",
  withdrawBank: "Thẻ ngân hàng rút tiền",
  drawMoney: "Số tiền mặt rút một lần",
  moneyPwd: "Mật khẩu tiền vốn",
  putSubmit: "Gửi đăng ký",
  lookOrder: "Tra cứu lưu lượng",
  drawNum: "Số lần rút tiền miễn phí còn lại hôm nay",
  strategy: "Phí thực hiện cần thiết",
  totalMoney: "Tổng số dư tài khoản",
  times: "Số lần",
  maxDrawMoney: "Số tiền rút cao nhất trong một lần",
  dayTimes: "Số lần đã rút hôm nay",
  nowBetNum: "Tổng cược hợp lệ hiện tại",
  drawNeedBet: "Tổng cược hợp lệ cần cho rút",
  strategyInfo: "Giải thích phí thực hiện",
  drawNum: "Số lần rút tiền miễn phí",
  strategyInfo1: "Sau khi vượt quá số lần, dựa theo số tiền rút mỗi lần",
  strategyInfo2: "Phí thực hiện thu",
  strategyInfo3: "Sau khi vượt quá số lần, theo",
  sureSetWithPwd: "Nhấp xác nhận thiết lập mật khẩu rút tiền",
  sureSetBank: "Nhấp xác nhận thiết lập thẻ ngân hàng",

  againPay: "Nạp tiền tiếp",
  againPayleft: "Lập tức có thể thăng cấp",
  withdrawPwd: "Mật khẩu rút tiền",
  setText: "Thiết lập",
  lastLogin: "Đăng nhập lần trước",
  transferOrderId: "Số đơn chuyển khoản",
  sysTo: "Chuyển khoản từ tài khoản hệ thống vào",
  fromSys: "Chuyển khoản vào tài khoản hệ thống",
  rebateText: "Tiền thưởng đặt cược",
  withdrawOrder: "Lịch sử rút tiền",
  putTransferInfo: "Điền thông tin chuyển khoản",
  TransferType: "Chọn loại chuyển khoản",
  oldText: "Ban đầu",
  newText: "Mới",
  reNewText: "Xác nhận mới",
  twoInput: "Nhập hai lần",
  notSame: "Không khớp",
  platformAndOrder: "Nền tảng / Số đơn",
  betAndEndTime: "Đặt cược / Thời gian kết toán",
  nameAndPlayName: "Tên gọi trò chơi / Cách chơi",
  halfWon: "Thắng một nửa",
  halfLose: "Thua một nửa",
  won: "Thắng",
  lose: "Thua",
  draw: "Ván hòa",
  waiting: "Đang chờ",
  running: "Đang tiến hành",
  void: "Hủy bỏ",
  refund: "Hoàn phí",
  settle: "Tính tiền",
  invalid: "Không có hiệu lực",
  closeSettle: "Đã kết toán",
  noSettle: "Chưa kết toán",
  cancelCodeOrder: "Hủy bỏ đơn đặt cược của ván được chỉ định",
  cancelOrder: "Hủy bỏ đơn đặt cược được chỉ định",
  betting: "Đang đặt cược",
  cash: "Rút đơn tiền mặt",
  dangerous: "Hủy bỏ nguy hiểm",
  restore: "Phục hồi",
  userCenter: "Trung tâm người sử dụng",
  sureGoIndex: "Nhấp xác nhận trở về trang chủ",
  noLoginRe: "Đăng nhập không thành công, vui lòng đăng nhập lại.",
  loading: "Đang tải",
  interceptorRrror: "Yêu cầu máy chặn gợi ý phát sinh sai sót",
  networkOutage: "Nối kết quá giờ, hãy kiểm tra mạng, sau đó quét mới mặt trang.",
  canDrawNum: "Số lần rút tiền hiện có",
}