var lang = {
  moneyChange: "Penukaran kuota",
  totalPay: "Jumlah nilai tambah nilai",
  totalWithdraw: "Jumlah pengeluaran wang tunai",
  fandian: "Rebat perolehan",
  noSet: "Belum tersedia",
  needPay: "Deposit diperlukan",
  sport: "Perlawanan sukan",
  egame: "Permainan elektronik",
  live: "Kasino langsung",
  chess: "Permainan catur dan kad",
  esport: "e-perlawanan",
  fish: "Permainan memancing",
  betAmount: "Jumlah pertaruhan",
  winAmount: "Nilai hadiah wang",
  rebateAmount: "Amaun rebat",
  betNum: "Jumlah pertaruhan yang sah",
  indexHint: "Perolehan bersih=Nilai hadiah wang+rebat draw+rebat pertaruhan+rebat agen+promosi+ganjaran aktiviti-amaun pertaruhan",
  indexRemark: "Nota: Statistik mengganggu prestasi sistem, dan hasil statistik akan disimpan dalam cache2minit",

  securityLevel: "Tahap keselamatan",
  low: "Rendah",
  middle: "Sederhana",
  high: "Tinggi",
  lastLoginTime: "Maklumat log masuk terakhir",
  loginTime: "Masa log masuk",
  lastLoginIp: "IP log masuk terakhir",
  loginIp: "IPlog masuk",
  basicInfo: "Maklumat asas",
  realNameHint: "Sekiranya anda perlu mengubah nama sebenar anda, sila hubungi khidmat pelanggan",
  realName: "Nama sebenar",
  loginPwd: "Kata laluan log masuk",
  loginPwdHint: "Kata laluan log masuk terdiri daripada6-30nombor dan huruf",
  okPwdHint: "Kata laluan pengeluaran terdiri daripada4-20nombor dan huruf. Anda perlu memasukkan kata laluan pengeluaran untuk melakukan pengeluaran dalam talian",
  phone: "Nombor telefon bimbit",
  phoneHint: "Pengikatan telefon bimbit dapat meningkatkan tahap keselamatan akaun, menjadikan akaun lebih selamat dan sihat",
  email: "Emel",
  emailHine: "Pengikatan emel dapat meningkatkan tahap keselamatan akaun, menjadikan akaun lebih selamat dan sihat",
  weChat: "WeChat",
  weChatHint: "Pengikatan WeChat dapat meningkatkan tahap keselamatan akaun, menjadikan akaun lebih selamat dan sihat",
  qqHint: "PengikatanQQdapat meningkatkan tahap keselamatan akaun, menjadikan akaun lebih selamat dan sihat",
  facebookHint: "PengikatanFacebookdapat meningkatkan tahap keselamatan akaun, menjadikan akaun lebih selamat dan sihat",
  set: "Pergi set",
  edit: "Ubahsuai",
  look: "Lihat",
  infoLook: "Lihat maklumat asas",
  inputOld: "Sila masukkanQQlama",
  inputNew: "Sila masukkanQQbaru",
  inputReNew: "Sila sahkanQQbaru",
  reset: "Set semula",
  confirm: "Sahkan",
  cancel: "Batal",
  formatRrror: "Format tidak betul",
  pleaseInput: "Sila masukkan ",
  canNotEmpty: "Tidak boleh biarkan kosong",
  canNotSame: "QQlama danQQbarutidak boleh sama",
  twoPutInconformity: "Kedua-dua entriQQtidak konsisten",
  submiting: "Sedang menghantar",

  welcomeLogin: "Selamat datang dan log masuk",
  pwdEdit: "Tukar kata laluan",
  message: "Mesej intranet",
  notice: "Pengumuman laman web",
  imPay: "Tambah nilai sekarang",
  applyAgency: "Permohonan agen",
  pleaseSelect: "Sila pilih ",
  from: "Dari",
  shiftTo: "Pindahan masuk",
  outMoney: "Kuota pindahan keluar",
  putHint: "Sila masukkan isi kandungan ",
  surePut: "Sahkan pindahan keluar",
  moneyChangeHint: "Nota: Penukaran tanpa kuota telah diaktifkan, kuota akan ditukar secara automatik selepas memasuki permainan.",
  limitMoney: "Kuota",
  refresh: "Muat semula",
  sysMoney: "Kuota sistem",

  status: "Status",
  shiftToType: "Kaedah pindahan masuk",
  sanFangType: "Kategori tiga pihak",
  transferTime: "Masa pindahan pembayaran",
  transferType: "Kategori pindahan pembayaran",
  platformText: "Kategori permainan",
  transferMoney: "Amaun pindahan pembayaran",
  transferStatus: "Status pindahan pembayaran",
  allStatus: "Semua status",
  transferError: "Pindahan pembayaran gagal",
  transferSuccess: "Pindahan pembayaran berjaya",
  transfering: "Sedang diproses",
  moneyChangeAllType: "Semua kaedah pindahan masuk",
  fromSysToSf: "Pemindahan dari sistem ke tiga pihak",
  fromSfToSys: "Pemindahan dari tiga pihak ke sistem",
  successText: "Berjaya",
  errorText: "Gagal",

  addText: "Tambah",
  bankRealName: "Nama pemegang akaun",
  bankName: "Cawangan bank",
  bankCardNo: "Nombor kad",
  bankStatus: "Status",
  bankTime: "Masa pengikatan",
  addBank: "Tambah kad bank",
  bankHint: "Nota: Anda perlu memberikan maklumat nombor kad bank terikat yang terakhir menggunakannya untuk menambah kad bank terikat!",
  lastBankName: "Nama pemegang akaun kad bank terikat terakhir",
  lastBankCardNo: "Nombor kad bank terikat terakhir",
  lastBank: "Akaun bank",
  pleaseBank: "Sila pilih cawangan bank",
  bankName: "Nama pemegang akaun",
  putBankRealName: "Isi nama sebenar pemegang kad bank",
  putAddress: "Isi alamat cawangan kad bank",
  putNoHint: "Hanya dapat masukkan 7-25nombor sahaja",
  sureBank: "Sahkan bank",
  rePutBankNo: "Masukkan nombor kad bank sekali lagi",
  bankOtherHint: "Sila ikat nombor telefon bimbit anda terlebih dahulu untuk memastikan keselamatan dana dalam akaun anda",

  scoreExChange: "Penebusan mata",
  changeType: "Kategori perubahan",
  beforeScore: "Mata sebelum perubahan",
  scoreNum: "Mata yang diubah",
  afterScore: "Mata selepas perubahan",
  scoreTime: "Masa perubahan (sistem)",
  remarkText: "Nota",
  money: "Baki akaun",
  score: "Baki mata",
  exchangeType: "Kaedah pertukaran",
  moneyToScore: "Pertukaran mata dengan wang tunai",
  scoreToMoney: "Pertukaran wang tunai dengan mata",
  exchangeScale: "Ratio pertukaran",
  exchangeMin: "Nilai minimum untuk setiap pertukaran",
  exchangeMax: "Nilai maksimum untuk setiap pertukaran",
  exchangeNum: "Bilangan pertukaran",
  exchangeToNum: "Bilangan penukaran",
  notSet: "Belum dikonfigurasikan untuk sementara ini",
  allText: "Semua",
  typeActiveSub: "Aktiviti tolak mata",
  memberSign: "Daftar masuk ahli",
  depositPresented: "Bonus deposit",
  peopleAdd: "Tambah secara manual",
  peopleSub: "Tolak secara manual",
  activeAdd: "Aktiviti pemberian mata",
  active: "Promosi",

  orderId: "Nombor borang pesanan",
  beforeNum: "Jumlah pertaruhan sebelum perubahan",
  betNum: "Jumlah pertaruhan yang diubah",
  afterNum: "Jumlah pertaruhan selepas perubahan",
  beforeDrawNeed: "Syarat pengeluaran sebelum perubahan",
  drawNeed: "Syarat pengeluaran",
  afterDrawNeed: "Syarat pengeluaran selepas perubahan",
  totalText: "Total",
  regPresent: "Hadiah pendaftaran",
  redPacket: "Ang pow",
  everyType: "Ganjaran harian, kerugian mingguan",
  payText: "Deposit",
  activeWin: "Kemenangan aktiviti",
  classPresent: "Hadiah naik taraf",
  fandianEarnings: "Rebat perolehan agen",
}
