var lang = {
  withdrawPwdNoHint: "Withdrawal password not set",
  bankNoHint: "Bank card not set",
  canWithdraw: "Amount of withdrawable",
  strategyfeeValue: "Charge fee",
  withdrawBank: "Bank card of withdrawal",
  drawMoney: "Amount of withdrawal every single time",
  moneyPwd: "Funds password",
  putSubmit: "Submit apply",
  lookOrder: "Check the valid betting amount",
  drawNum: "The remaining number of no charge withdrawal today",
  strategy: "Charge fee",
  totalMoney: "Account total balance",
  times: "The number of times",
  maxDrawMoney: "Maximum amount of withdrawal every single time",
  dayTimes: "Today has been the number of withdrawal",
  nowBetNum: "Betting amount now",
  drawNeedBet: "The amount of betting for the withdrawal",
  strategyInfo: "Description of service charge",
  drawNum: "The number of no charge withdrawal",
  strategyInfo1: "After over the number of no charge withdrawal, charge with amount of withdrawal each time",
  strategyInfo2: "Service charge fee",
  strategyInfo3: "After over the number of",
  sureSetWithPwd: "Click confirm to set the withdrawal password",
  sureSetBank: "Click confirm to set the bank card",
  againPay: "Deposit again",
  againPayleft: "${0} can level up",
  withdrawPwd: "Withdrawal password",
  setText: "Set",
  lastLogin: "Login last time",
  transferOrderId: "Transfer order NO.",
  sysTo: "Transfer from system account to",
  fromSys: "Transfer to system account",
  rebateText: "Rebate",
  withdrawOrder: "Withdrawal records",
  putTransferInfo: "Enter the transfer information",
  TransferType: "Select the transfer type",
  oldText: "Old",
  newText: "New",
  reNewText: "Check the new",
  twoInput: "The twice you enter",
  notSame: "Different",
  platformAndOrder: "Platform / Order NO.",
  betAndEndTime: "Bet / Settlement time",
  nameAndPlayName: "Game name / Game type",
  halfWon: "Win half",
  halfLose: "Lose half",
  won: "Win",
  lose: "Lose",
  draw: "Tie",
  waiting: "Waitting",
  running: "In processing",
  void: "Invalid",
  refund: "refund betting",
  settle: "Settlement betting",
  invalid: "Invalid",
  closeSettle: "Already settlement",
  noSettle: "Not yet settlement",
  cancelCodeOrder: "Cancel designated round betting order",
  cancelOrder: "Cancel designated betting order",
  betting: "In Betting",
  cash: "Cancel order trans cash",
  dangerous: "Dangerous bet, so invalid",
  restore: "Restore",
  userCenter: "User center",
  sureGoIndex: "Click Confirm to return home page",
  noLoginRe: "Login failed, please login again",
  loading: "In loading",
  interceptorRrror: "Ask interceptor tips error",
  networkOutage: "Timed out, please check your network and reflash page",
  rechargeTitle: "Deposit",
  canDrawNum: "The number of withdrawal available today",
}
