var lang = {
moneyChange:"Chuyển ví",
totalPay:"Tổng số tiền nạp",
totalWithdraw:"Tổng số tiền rút",
fandian:"Hoàn trả lợi nhuận",
againPay:"Nạp tiếp 10 tệ là có thể thăng cấp",
againPay:"Nạp tiếp 10 tệ là có thể thăng cấp",
noSet:"Chưa thiết lập",
needPay:"Cần gửi tiền",
sport:"Thi đấu thể thao",
egame:"Trò chơi điện tử",
live:"Sòng bạc trực tuyến",
chess:"Trò chơi bài lá",
esport:"Trò chơi thể thao điện tử",
fish:"Trò chơi bắt cá",
betAmount:"Số tiền đặt cược",
winAmount:"Số tiền trúng thưởng",
rebateAmount:"Số tiền thưởng đặt cược",
betNum:"Lượng quét mã có hiệu lực",
indexHint:"Lợi nhuận thuần = Số tiền trúng thưởng + Tiền trả hòa + Tiền thưởng đặt cược + Tiền thưởng đặt cược đại lý + Ưu đãi + Phần thưởng hoạt động - Số tiền đặt cược",
indexRemark:"Ghi chú: Thống kê tính năng hệ thống tiêu hao hơn, kết quả thống kê sẽ lưu 2 phút",
securityLevel:"Cấp an toàn",
low:"Thấp",
middle:"Vừa",
high:"Cao",
lastLoginTime:"Lần gần nhất đăng nhập thông tin:",
loginTime:"Thời gian đăng nhập",
lastLoginIp:"Lần gần nhất đăng nhập IP",
loginIp:"Đăng nhập IP",
basicInfo:"Thông tin cơ bản",
realNameHint:"Nếu cần sửa đổi họ và tên thật, vui lòng liên hệ Dịch vụ Khách hàng.",
realName:"Họ và tên thật",
loginPwd:"Mật khẩu",
loginPwdHint:"Mật khẩu đăng nhập là 6-30 chữ số và chữ cái",
okPwdHint:"Mật khẩu rút tiền là 4-20 chữ số và chữ cái, khi rút tiền trực tuyến cần nhập mật khẩu rút tiền mới được rút tiền.",
phone:"Số điện thoại di động",
phoneHint:"Ràng buộc điện thoại di động có thể tăng thêm cấp an toàn số tài khoản, tài khoản càng thêm an toàn và lành mạnh.",
email:"Hòm thư điện tử",
emailHine:"Ràng buộc hòm thư điện tử có thể tăng thêm cấp an toàn số tài khoản, tài khoản càng thêm an toàn và lành mạnh.",
weChat:"Wechat",
weChatHint:"Ràng buộc WeChat có thể tăng thêm cấp an toàn số tài khoản, tài khoản càng thêm an toàn và lành mạnh.",
qqHint:"Ràng buộc QQ có thể tăng thêm cấp an toàn số tài khoản, tài khoản càng thêm an toàn và lành mạnh",
facebookHint:"Ràng buộc Facebook có thể tăng thêm cấp an toàn số tài khoản, tài khoản càng thêm an toàn và lành mạnh",
set:"Xin vui lòng thiết lập",
edit:"Sửa đổi",
look:"Tra cứu",
infoLook:"Tra cứu thông tin cơ bản",
inputOld:"Xin vui lòng nhập QQ ban đầu",
inputNew:"Xin vui lòng nhập QQ mới",
inputReNew:"Xin vui lòng xác nhận QQ mới",
reset:"Lập lại",
confirm:"Đăng ký",
cancel:"Hủy bỏ",
formatRrror:"Định dạng không chính xác",
pleaseInput:"Xin vui lòng nhập",
canNotEmpty:"Không được để trống",
canNotSame:"QQ ban đầu  không được giống QQ mới",
twoPutInconformity:"Hai lần nhập QQ không khớp",
submiting:"Đang gửi đi...",
welcomeLogin:"Chào mừng đăng nhập",
pwdEdit:"Sửa đổi mật khẩu",
message:"Tin nhắn nội bộ",
notice:"Thông báo trên mạng",
imPay:"Nạp ngay",
applyAgency:"Đăng ký Đại lý",
pleaseSelect:"Xin vui lòng chọn",
from:"Từ",
shiftTo:"Chuyển khoản vào",
outMoney:"Hạn ngạch chuyển ra",
putHint:"Xin vui lòng nhập nội dung",
surePut:"Xác nhận chuyển ra",
moneyChangeHint:"Ghi chú: Miễn chuyển đổi hạn ngạch đã mở, trực tiếp vào trò chơi là có thể tự động chuyển vào hạn ngạch!",
limitMoney:"Hạn ngạch",
refresh:"Quét mới",
sysMoney:"Hạn ngạch hệ thống",
status:"Trạng thái",
shiftToType:"Phương thức chuyển vào",
sanFangType:"Loại hình ba bên",
transferTime:"Thời gian chuyển khoản",
transferType:"Loại chuyển khoản",
platformText:"Loại hình trò chơi",
transferMoney:"Số tiền chuyển khoản",
transferStatus:"Trạng thái chuyển khoản",
allStatus:"Toàn bộ trạng thái",
transferError:"Chuyển khoản không thành công",
transferSuccess:"Chuyển khoản thành công",
transfering:"Đang xử lý",
moneyChangeAllType:"Phương thức chuyển vào toàn bộ",
fromSysToSf:"Chuyển vào ba bên từ hệ thống",
fromSfToSys:"Chuyển vào hệ thống từ ba bên",
successText:"Thành công",
errorText:"Không thành công",
addText:"Thêm mới",
bankRealName:"Ngân hàng",
bankName:"Ngân hàng",
bankCardNo:"Số thẻ",
bankStatus:"Trạng thái",
bankTime:"Thời gian ràng buộc",
addBank:"Thêm số thẻ ngân hàng",
bankHint:"Ghi chú: Thêm thẻ ngân hàng ràng buộc phải cung cấp thông tin số thẻ ngân hàng đang sử dụng được ràng buộc gần đây nhất!",
lastBankName:"Họ và tên mở thẻ ngân hàng ràng buộc gần đây nhất",
lastBankCardNo:"Số thẻ ngân hàng ràng buộc gần đây nhất",
lastBank:"Ngân hàng mở tài khoản",
pleaseBank:"Xin vui lòng chọn ngân hàng được mở",
bankName:"Họ tên người mở tài khoản",
putBankRealName:"Điền họ và tên thật của thẻ ngân hàng",
putAddress:"Điền địa chỉ mở ngân hàng thẻ ngân hàng",
putNoHint:"Chỉ có thể nhập 7-25 chữ số",
sureBank:"Xác nhận ngân hàng",
rePutBankNo:"Nhập lại số thẻ thẻ ngân hàng",
bankOtherHint:"Vì an toàn vốn tài khoản của bạn, vui lòng ràng buộc số điện thoại di động trước.",
scoreExChange:"Chuyển đổi tích điểm",
changeType:"Loại hình thay đổi",
beforeScore:"Tích điểm trước khi thay đổi",
scoreNum:"Tích điểm khi thay đổi",
afterScore:"Tích điểm sau khi thay đổi",
scoreTime:"Thời gian thay đổi (hệ thống)",
remarkText:"Ghi chú",
money:"Số dư tài khoản",
score:"Số dư tích điểm",
exchangeType:"Phương thức chuyển đổi",
moneyToScore:"Tiền mặt đổi tích điểm",
scoreToMoney:"Tích điểm đổi tiền mặt",
exchangeScale:"Tỷ lệ chuyển đổi",
exchangeMin:"Giá trị chuyển đổi nhỏ nhất trong một lần",
exchangeMax:"Giá trị chuyển đổi lớn nhất trong một lần",
exchangeNum:"Số lượng chuyển đổi",
exchangeToNum:"Số lượng chuyển đổi",
notSet:"Tạm thời không sắp xếp",
allText:"Toàn bộ",
typeActiveSub:"Khấu trừ tích điểm hoạt động",
memberSign:"Hội viên đăng ký có mặt",
depositPresented:"Tặng thêm khi gửi tiền",
peopleAdd:"Thêm vào bằng tay",
peopleSub:"Khấu trừ bằng tay",
activeAdd:"Tặng tích điểm hoạt động",
active:"Hoạt động ưu đãi",
orderId:"Mã số đơn đặt",
beforeNum:"Lượng quét mã trước khi thay đổi",
betNum:"Lượng quét mã khi thay đổi",
afterNum:"Lượng quét mã sau khi thay đổi",
beforeDrawNeed:"Yêu cầu rút tiền trước khi thay đổi",
drawNeed:"Yêu cầu rút tiền",
afterDrawNeed:"Yêu cầu rút tiền sau khi thay đổi",
totalText:"Tổng cộng",
regPresent:"Đăng ký tặng",
redPacket:"Lì xì",
everyType:"Thêm thưởng mỗi ngày, lỗ tổn mỗi tuần",
payText:"Gửi tiền",
activeWin:"Trúng thưởng hoạt động",
classPresent:"Tặng khi nâng cấp",
fandianEarnings:"Thu nhập tiền thưởng đặt cược đại lý",
}
